### ISSUE TITLE
[FEAT]: Automatic Sourcing of This Workspace in the Container

### ISSUE THREAD

**Issue by cooperj** [LCAS/limo_ros2#15]
### Description

When using the container on a Limo, you have to run `. install/setup.bash &&` in every terminal before you can use ros2. 

This can become tiresome when requiring lots of terminal windows to be opened.

If it was added to the `bashrc` you would not need to run this command. 

After testing on one robot, it is working as intended.

### Additional Information

I'm happy to open a PR for this, but all that needs to be done is add another line to the Dockerfile alongside the previous sourcing…

https://github.com/LCAS/limo_ros2/blob/057e9a5ef5b74f45ffc50760552e57b0af9a1c55/.devcontainer/Dockerfile#L85

```Dockerfile
RUN echo "source /workspaces/limo_ros2/install/setup.bash" >> /etc/bash.bashrc 
```

You could look at having it work regardless of the folder's name, but this will work in most (if not all) cases.

**Comment by marc-hanheide** [comment]
I think this already working with #17
