### ISSUE TITLE
[BUG]: Make the real Limos work with docker-compose image

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/limo_ros2#18]
### Description of the bug

A few things to tidy up:

- [ ] add `8.8.8.8` as DNS?!
- [ ] make some space, uninstall libreoffice and other things that are definitely not needed, e.g `docker system prune -a` and `sudo apt-get purge "libreoffice*"`, check there are at least 12Gb (`df -h /`), e.g. remove checked out stuff from home etc
- [ ] install docker compose: `curl https://raw.githubusercontent.com/LCAS/limo_ros2/humble/.devcontainer/on_limo/install-docker-compose.sh | bash -`
- [ ] run `docker login -u lcas -p lincoln lcas.lincoln.ac.uk`
- [ ] download docker-compose file: `curl -o ~/docker-compose.yaml https://raw.githubusercontent.com/LCAS/limo_ros2/humble/.devcontainer/on_limo/docker-compose.yaml`
- [ ] `docker compose up -d && docker compose logs -f`
- [ ] resize the boot partition to 64GBs instead of the 32GBs

### Steps To Reproduce

In the end, we must ensure that the instructions in https://github.com/LCAS/teaching/wiki/Using-the-real-Limo-Robot work out of the box without additional installation required. Please test.

**Comment by cooperj** [comment]
joining??!?!?

**Comment by jondave** [comment]
sudo apt remove --purge libreoffice*

**Comment by cooperj** [comment]
resize the boot partition to 64GBs instead of the 32GBs

**Comment by marc-hanheide** [comment]
> resize the boot partition to 64GBs instead of the 32GBs

add that to the sub tasks above?

**Comment by cooperj** [comment]
Got a fresh robot out to run this against - that's completed. Awaiting @marc-hanheide to test and will repeat with the others during maintenance.

**Comment by cooperj** [comment]
RVIZ not opening due to not having a configuration file in the [ros2-teaching-ws](https://github.com/LCAS/ros2-teaching-ws/) repo.

Copied the `.rviz` file from the [limo_ros2](https://github.com/LCAS/limo_ros2/tree/humble/src) repo… and it worked. What should we do? Should we add the files to the teaching workspace, or am I doing something wrong?

**Comment by marc-hanheide** [comment]
I never gave them an rviz config so far. Please feel free to add to uol_tidybot package in here: https://github.com/LCAS/teaching/tree/2324-devel/uol_tidybot/launch with a pull request. It's a nice feature, but I want them to understand how to use rviz2, so didn't offer an off the shelf solution.

**Comment by jondave** [comment]
README file incorrect
`ros2 launch limo_bringup cartographer.launch.py`
should be
`ros2 launch limo_navigation cartographer.launch.py`

**Comment by cooperj** [comment]
As I didn't open this issue (and I'm not an owner of this repo); I can't close it.

Consider this as closed and completed ✅
